### ISSUE TITLE
Create a middleware to parse request params into a map[string]string

### ISSUE THREAD

**Issue by opensaucerer** [BLACHEINC-ORG/golang-server-template#10]
Like we did with the issue here #8 we need a way to be able to parse request params as well and make it available in the request context. 
We can always do `mux.Vars(r)` as the time but surely that's a lot of repetition...and a middleware with help keep things structured. 

Also, we'll need one for `ParamsF` and `ParamsH`

**Comment by Funmi4194** [comment]
Okay, I will work on it . Thank you🙇🏽‍♀️
